# Generated by Django 4.1.5 on 2023-01-21 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diskpeeker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiskUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=240, verbose_name='Device')),
                ('type', models.CharField(max_length=240, verbose_name='Type')),
                ('total', models.IntegerField(verbose_name='Total')),
                ('used', models.IntegerField(verbose_name='Used')),
            ],
        ),
        migrations.CreateModel(
            name='FullDiskInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=240, verbose_name='Device')),
                ('name', models.CharField(max_length=240, verbose_name='Name')),
                ('type', models.CharField(max_length=240, verbose_name='Type')),
                ('total', models.IntegerField(verbose_name='Total')),
                ('used', models.IntegerField(verbose_name='Used')),
                ('hidden', models.BooleanField(verbose_name='Hidden')),
            ],
        ),
    ]
